name: Send hello to webhook
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          URL="https://webhook.site/2c9bd304-bd77-4157-8b8e-1ee4a93ec671"
          BODY="{\"message\": \"hello\"}"
          RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d "$BODY" "$URL")
          echo "$RESPONSE"
