name: Greeting in issue

on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet issue
        run: echo "Hello" | gh issue comment ${{ github.event.issue.number }}
