name: Send message to webhook

on:
  push:
    branches: [ main ]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"message":"Hello"}' https://webhook.site/2c9bd304-bd77-4157-8b8e-1ee4a93ec671
